"use strict";

const fs = require("fs");
const path = require("path");
const Module = require("module");

const OUTPUT_TAB_WIDTH = 4;
const INPUT_TAB_STOPS = [0, 20, 32, 64];
const LINE_BREAK_PATTERN = /\r\n|\r|\n/;

function retabulate(line) {
	if (line.length === 0) {
		return "";
	}

	let outPosition = 0;
	let tabIndex = 0;
	let lastIndex = 0;
	let result = "";

	const advanceToReach = () => {
		const stop = INPUT_TAB_STOPS[tabIndex];
		const reach = Math.max(stop !== undefined ? stop : -Infinity, outPosition + 1);
		let next;
		while ((next = outPosition + OUTPUT_TAB_WIDTH - (outPosition % OUTPUT_TAB_WIDTH)) <= reach) {
			result += "\t";
			outPosition = next;
		}
		const spaces = reach - outPosition;
		if (spaces > 0) {
			result += " ".repeat(spaces);
			outPosition = reach;
		}
		tabIndex += 1;
	};

	advanceToReach();

	line.replace(/\t/g, (_match, offset) => {
		const segment = line.slice(lastIndex, offset);
		if (segment.length > 0) {
			result += segment;
			outPosition += segment.length;
		}
		advanceToReach();
		lastIndex = offset + 1;
		return "";
	});

	const tail = line.slice(lastIndex);
	if (tail.length > 0) {
		result += tail;
		outPosition += tail.length;
	}

	return result;
}

function clampIndex(value, min, max) {
	if (!Number.isFinite(value)) {
		return min;
	}
	if (value < min) {
		return min;
	}
	if (value > max) {
		return max;
	}
	return Math.floor(value);
}

function getLineInfo(source, rawIndex) {
	const index = clampIndex(rawIndex, 0, source.length);
	const before = source.slice(0, index);
	const lineParts = before.split(LINE_BREAK_PATTERN);
	const line = lineParts.length;
	const lastSegment = lineParts[lineParts.length - 1] ?? "";
	const lineStart = index - lastSegment.length;
	const rest = source.slice(index);
	const match = rest.match(LINE_BREAK_PATTERN);
	const lineEnd = match ? index + match.index : source.length;
	const lineText = source.slice(lineStart, lineEnd);
	return { index, line, lineStart, lineEnd, lineText };
}

function findLineBounds(source, index) {
	const { line, lineStart, lineEnd } = getLineInfo(source, index);
	return { line, lineStart, lineEnd };
}

function renderErrorContext(lineText, pointerOffset) {
	let displayLine = "";
	let pointerLine = "";
	let runningColumn = 1;
	let pointerColumn = 1;

	for (let pos = 0; pos < lineText.length; ++pos) {
		const ch = lineText[pos];
		if (ch === "\t") {
			const spaces = OUTPUT_TAB_WIDTH - ((runningColumn - 1) % OUTPUT_TAB_WIDTH);
			displayLine += " ".repeat(spaces);
			runningColumn += spaces;
			if (pos < pointerOffset) {
				pointerLine += " ".repeat(spaces);
				pointerColumn += spaces;
			}
			continue;
		}
		const code = ch.charCodeAt(0);
		const safeChar = code >= 0x20 && code !== 0x7f ? ch : " ";
		displayLine += safeChar;
		runningColumn += 1;
		if (pos < pointerOffset) {
			pointerLine += " ";
			pointerColumn += 1;
		}
	}

	if (pointerOffset >= lineText.length) {
		pointerColumn = runningColumn;
	}

	pointerLine += "^";

	return {
		displayLine,
		pointerLine,
		column: pointerColumn,
	};
}

function formatErrorWithLocation(source, options, rawIndex, baseMessage, explicitLocationLabel) {
	const { index, line, lineStart, lineEnd, lineText } = getLineInfo(source, rawIndex);
	const context = renderErrorContext(lineText, index - lineStart);
	let locationLabel;
	if (explicitLocationLabel !== undefined) {
		locationLabel = explicitLocationLabel;
	} else if (options && options.sourceName) {
		locationLabel = ` ${options.sourceName}`;
	} else {
		locationLabel = " source";
	}
	let message = `${baseMessage}${locationLabel} at line ${line}, column ${context.column}, offset ${index}.`;
	if (context.displayLine.length > 0 || lineEnd > lineStart) {
		message += `\n${context.displayLine}\n${context.pointerLine}`;
	} else {
		message += "\n^";
	}
	return message;
}

function formatThrownCompilerError(err, source, options) {
	if (err && typeof err === "object" && Number.isFinite(err.impalaOffset)) {
		const baseMessage = err.impalaMessage || (err.message ? err.message.split(" : ")[0] : "JSPEG impala compiler error");
		return formatErrorWithLocation(source, options, err.impalaOffset, baseMessage);
	}
	if (err && err.message) {
		return err.message;
	}
	return String(err);
}

//
// NOTE: The Impala compiler bundle under `impalaCompiler.js` is generated by the
// upstream JSPEG toolchain. Build-time hardening injects the safety helpers when
// regenerating the bundle, so the runner simply loads the emitted source verbatim.
//

function resolveCompilerExport(candidate) {
	if (typeof candidate === "function") {
		return candidate;
	}
	if (candidate && typeof candidate === "object") {
		return candidate.impalaCompiler || candidate.default || candidate.compile || candidate.compiler || candidate;
	}
	return undefined;
}

const GLOBAL_SENTINEL = Symbol("missing");

function withGlobalBindings(bindings, fn, preserve = []) {
	const keys = Array.from(new Set([...Object.keys(bindings), ...preserve]));
	const snapshot = {};
	for (const key of keys) {
		if (Object.prototype.hasOwnProperty.call(globalThis, key)) {
			snapshot[key] = globalThis[key];
		} else {
			snapshot[key] = GLOBAL_SENTINEL;
		}
	}
	try {
		for (const [key, value] of Object.entries(bindings)) {
			if (value === undefined) {
				delete globalThis[key];
			} else {
				globalThis[key] = value;
			}
		}
		return fn();
	} finally {
		for (const key of keys) {
			const value = snapshot[key];
			if (value === GLOBAL_SENTINEL) {
				delete globalThis[key];
			} else {
				globalThis[key] = value;
			}
		}
	}
}

function loadCompilerModule(compilerSource, compilerFilename) {
	return withGlobalBindings(
		{},
		() => {
			const compilerModule = new Module(compilerFilename, module);
			compilerModule.filename = compilerFilename;
			compilerModule.paths = Module._nodeModulePaths(path.dirname(compilerFilename));
			compilerModule.require = Module.createRequire(compilerFilename);
			compilerModule._compile(compilerSource, compilerFilename);
			return compilerModule.exports;
		},
		["createParserContext"],
	);
}

function compileWithJsImpala(source, options = {}) {
	const {
		compilerPath: compilerPathOption,
		compilerSource,
		sourceName,
		retabulate: shouldRetabulate = true,
		trailingNewline,
		randomId = 12345678,
	} = options;

	const compilerPath = compilerPathOption
		? path.resolve(compilerPathOption)
		: path.join(__dirname, "impalaCompiler.js");
	const compilerText = compilerSource ?? fs.readFileSync(compilerPath, "utf8");

	const outputLines = [];
	const compilerExports = loadCompilerModule(compilerText, compilerPath);
	const compilerFn = resolveCompilerExport(compilerExports);
	if (typeof compilerFn !== "function") {
		throw new Error("JSPEG impala compiler did not export a function");
	}

	const compilerOptions = sourceName !== undefined ? { sourceName } : undefined;
	const compileResult = withGlobalBindings(
		{
			output: (line) => outputLines.push(line),
			impalaRandomId: randomId,
		},
		() => {
			try {
				return compilerFn(source, compilerOptions);
			} catch (err) {
				throw new Error(formatThrownCompilerError(err, source, options));
			}
		},
		["createParserContext"],
	);
	const [ok, , index] = compileResult;
	if (!ok) {
		throw new Error(formatErrorWithLocation(source, options, index, "JSPEG impala compiler failed to compile"));
	}
	if (index !== source.length) {
		throw new Error(`JSPEG impala compiler stopped at ${index} of ${source.length}`);
	}

	if (outputLines.length === 0) {
		return "";
	}

	const formatted = shouldRetabulate ? outputLines.map(retabulate) : outputLines;
	let outputText = formatted.join("\n");

	if (trailingNewline === true || (trailingNewline === undefined && shouldRetabulate)) {
		outputText += "\n";
	} else if (!shouldRetabulate && trailingNewline !== true) {
		while (outputText.endsWith("\n")) {
			outputText = outputText.slice(0, -1);
		}
	}

	return outputText;
}

module.exports = {
	compileWithJsImpala,
};
